import type { CrisisIncident } from "@/app/lib/crisis/types";

const now = Date.now();
const dayMs = 86_400_000;

const isoDaysAgo = (daysAgo: number) =>
  new Date(now - daysAgo * dayMs).toISOString();

export const seedIncidents: CrisisIncident[] = [
  {
    id: "inc_001",
    title: "River overflow displaces households",
    summary:
      "Sustained rainfall triggered river overflow; temporary shelters are active and supply chains are stressed.",
    category: "flood",
    severity: "high",
    trust: "reported",
    source: "Local authority bulletin",
    country: "India",
    region: "Assam",
    lat: 26.2006,
    lon: 92.9376,
    occurredAt: isoDaysAgo(5),
    updatedAt: isoDaysAgo(3),
    affectedEstimate: 38_000,
  },
  {
    id: "inc_002",
    title: "Aftershock risk near affected settlements",
    summary:
      "Seismic activity continues with intermittent aftershocks; structural assessments underway across key facilities.",
    category: "earthquake",
    severity: "critical",
    trust: "verified",
    source: "Seismology institute",
    country: "Nepal",
    region: "Bagmati",
    lat: 27.7172,
    lon: 85.324,
    occurredAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(1),
    affectedEstimate: 112_000,
  },
  {
    id: "inc_003",
    title: "Wildfire smoke impacts air quality",
    summary:
      "Fire lines expanded due to dry winds; hospitals report increased respiratory cases and evacuation orders issued.",
    category: "wildfire",
    severity: "high",
    trust: "verified",
    source: "Emergency management agency",
    country: "United States",
    region: "California",
    lat: 37.7749,
    lon: -122.4194,
    occurredAt: isoDaysAgo(6),
    updatedAt: isoDaysAgo(2),
    affectedEstimate: 64_000,
  },
  {
    id: "inc_004",
    title: "Cholera alerts near coastal camps",
    summary:
      "Waterborne disease alerts rising; hygiene kits distribution is scaling with community health monitoring.",
    category: "epidemic",
    severity: "medium",
    trust: "reported",
    source: "Clinic network",
    country: "Mozambique",
    region: "Nampula",
    lat: -15.1165,
    lon: 39.2666,
    occurredAt: isoDaysAgo(9),
    updatedAt: isoDaysAgo(4),
    affectedEstimate: 19_500,
  },
  {
    id: "inc_005",
    title: "Localized conflict disrupts aid routes",
    summary:
      "Road closures affect medical deliveries; convoy coordination and safe-corridor verification in progress.",
    category: "conflict",
    severity: "critical",
    trust: "disputed",
    source: "Partner field reports",
    country: "Sudan",
    region: "Khartoum",
    lat: 15.5007,
    lon: 32.5599,
    occurredAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(1),
    affectedEstimate: 210_000,
  },
  {
    id: "inc_006",
    title: "Cyclone warnings issued for coastal belt",
    summary:
      "Storm tracks indicate potential landfall; early warnings broadcast and emergency supplies staged.",
    category: "storm",
    severity: "high",
    trust: "unverified",
    source: "Meteorological service",
    country: "Bangladesh",
    region: "Chattogram",
    lat: 22.3569,
    lon: 91.7832,
    occurredAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(0),
    affectedEstimate: 88_000,
  },
  {
    id: "inc_007",
    title: "Prolonged drought reduces crop yields",
    summary:
      "Water access constraints deepen; food security monitoring flags supply gaps in remote districts.",
    category: "drought",
    severity: "medium",
    trust: "reported",
    source: "Agriculture extension reports",
    country: "Kenya",
    region: "Turkana",
    lat: 3.3122,
    lon: 35.5658,
    occurredAt: isoDaysAgo(21),
    updatedAt: isoDaysAgo(7),
    affectedEstimate: 156_000,
  },
  {
    id: "inc_008",
    title: "Landslides block access to mountain villages",
    summary:
      "Slope failures after rain have blocked roads; aerial assessment requested for isolated settlements.",
    category: "landslide",
    severity: "high",
    trust: "verified",
    source: "Rapid assessment team",
    country: "Indonesia",
    region: "West Java",
    lat: -6.9175,
    lon: 107.6191,
    occurredAt: isoDaysAgo(8),
    updatedAt: isoDaysAgo(6),
    affectedEstimate: 27_000,
  },
  {
    id: "inc_009",
    title: "Flash flooding impacts urban drainage",
    summary:
      "Short-duration intense rainfall overwhelmed drainage systems; transit disruptions and temporary shelters opened.",
    category: "flood",
    severity: "medium",
    trust: "unverified",
    source: "Civic monitoring channel",
    country: "Brazil",
    region: "São Paulo",
    lat: -23.5505,
    lon: -46.6333,
    occurredAt: isoDaysAgo(4),
    updatedAt: isoDaysAgo(2),
    affectedEstimate: 41_000,
  },
  {
    id: "inc_010",
    title: "Heat-driven wildfire risk escalates",
    summary:
      "Fire weather index rises; controlled burns paused and community alerts issued in adjacent zones.",
    category: "wildfire",
    severity: "medium",
    trust: "reported",
    source: "Regional fire service",
    country: "Australia",
    region: "New South Wales",
    lat: -33.8688,
    lon: 151.2093,
    occurredAt: isoDaysAgo(12),
    updatedAt: isoDaysAgo(9),
    affectedEstimate: 52_000,
  },
];
