import type { HealthcareFacility } from "@/lib/crisis/types";

const now = Date.now();
const dayMs = 86_400_000;

const isoDaysAgo = (daysAgo: number) =>
  new Date(now - daysAgo * dayMs).toISOString();

/**
 * Seed dataset: healthcare facilities across India with specialty
 * coverage gaps. Each record represents a facility and describes
 * the desert gap it sits in (or is near).
 */
export const seedFacilities: HealthcareFacility[] = [
  {
    id: "fac_001",
    title: "Guwahati Medical College",
    summary:
      "Government tertiary hospital serving Assam with limited oncology infrastructure. Nearest radiotherapy unit is 400 km away; cancer patients face severe travel burdens.",
    category: "oncology",
    gapSeverity: "critical",
    confidence: "govt-verified",
    source: "National Health Mission data",
    country: "India",
    state: "Assam",
    district: "Kamrup Metropolitan",
    facilityType: "tertiary-hospital",
    beds: 1200,
    specialists: 8,
    lat: 26.1445,
    lon: 91.7362,
    occurredAt: isoDaysAgo(5),
    updatedAt: isoDaysAgo(1),
    affectedPopulation: 4_200_000,
  },
  {
    id: "fac_002",
    title: "Jodhpur District Hospital",
    summary:
      "District hospital covering western Rajasthan with no dedicated dialysis unit. Patients requiring hemodialysis travel to Jaipur or Udaipur for routine sessions.",
    category: "dialysis",
    gapSeverity: "critical",
    confidence: "govt-verified",
    source: "CBHI Health Statistics",
    country: "India",
    state: "Rajasthan",
    district: "Jodhpur",
    facilityType: "district-hospital",
    beds: 500,
    specialists: 3,
    lat: 26.2389,
    lon: 73.0243,
    occurredAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(1),
    affectedPopulation: 3_600_000,
  },
  {
    id: "fac_003",
    title: "Bastar CHC Network",
    summary:
      "Community health centers in Bastar division lack emergency trauma capability. Road accident victims face 3–5 hour transfers to Raipur for surgical intervention.",
    category: "emergency-trauma",
    gapSeverity: "critical",
    confidence: "survey-reported",
    source: "NFHS-5 survey data",
    country: "India",
    state: "Chhattisgarh",
    district: "Bastar",
    facilityType: "chc",
    beds: 120,
    specialists: 2,
    lat: 19.1071,
    lon: 81.9535,
    occurredAt: isoDaysAgo(7),
    updatedAt: isoDaysAgo(3),
    affectedPopulation: 1_400_000,
  },
  {
    id: "fac_004",
    title: "Patna Medical College & Hospital",
    summary:
      "Large tertiary facility with overloaded cardiology department. Cath lab serves entire southern Bihar; wait times exceed 6 weeks for elective procedures.",
    category: "cardiology",
    gapSeverity: "severe",
    confidence: "govt-verified",
    source: "MoHFW Infrastructure Report",
    country: "India",
    state: "Bihar",
    district: "Patna",
    facilityType: "tertiary-hospital",
    beds: 2000,
    specialists: 12,
    lat: 25.6093,
    lon: 85.1376,
    occurredAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(1),
    affectedPopulation: 9_800_000,
  },
  {
    id: "fac_005",
    title: "Churachandpur District Hospital",
    summary:
      "Only maternity facility in southern Manipur hills. High maternal mortality rate due to single delivery room and no blood bank on site.",
    category: "maternity",
    gapSeverity: "critical",
    confidence: "survey-reported",
    source: "NFHS-5 survey data",
    country: "India",
    state: "Manipur",
    district: "Churachandpur",
    facilityType: "district-hospital",
    beds: 100,
    specialists: 1,
    lat: 24.334,
    lon: 93.6747,
    occurredAt: isoDaysAgo(10),
    updatedAt: isoDaysAgo(5),
    affectedPopulation: 270_000,
  },
  {
    id: "fac_006",
    title: "Lucknow KGMU Pediatrics Wing",
    summary:
      "Major pediatric referral center for UP. NICU capacity exhausted; neonatal mortality remains elevated in surrounding districts with no SNCU coverage.",
    category: "pediatrics",
    gapSeverity: "severe",
    confidence: "govt-verified",
    source: "National Health Mission data",
    country: "India",
    state: "Uttar Pradesh",
    district: "Lucknow",
    facilityType: "tertiary-hospital",
    beds: 3000,
    specialists: 18,
    lat: 26.8467,
    lon: 80.9462,
    occurredAt: isoDaysAgo(4),
    updatedAt: isoDaysAgo(2),
    affectedPopulation: 19_800_000,
  },
  {
    id: "fac_007",
    title: "Dharwad Mental Health Center",
    summary:
      "One of few dedicated mental health facilities in northern Karnataka. Psychiatrist-to-population ratio is 1:500,000 across the region.",
    category: "mental-health",
    gapSeverity: "severe",
    confidence: "crowd-sourced",
    source: "NIMHANS community survey",
    country: "India",
    state: "Karnataka",
    district: "Dharwad",
    facilityType: "specialty-center",
    beds: 60,
    specialists: 4,
    lat: 15.4589,
    lon: 75.0078,
    occurredAt: isoDaysAgo(15),
    updatedAt: isoDaysAgo(7),
    affectedPopulation: 1_800_000,
  },
  {
    id: "fac_008",
    title: "Ranchi Orthopedic Referral Center",
    summary:
      "Tribal districts in Jharkhand lack orthopedic surgical capacity. Mining injuries often require emergency transfers spanning 200+ km to Ranchi.",
    category: "orthopedics",
    gapSeverity: "severe",
    confidence: "survey-reported",
    source: "CBHI Health Statistics",
    country: "India",
    state: "Jharkhand",
    district: "Ranchi",
    facilityType: "district-hospital",
    beds: 400,
    specialists: 6,
    lat: 23.3441,
    lon: 85.3096,
    occurredAt: isoDaysAgo(8),
    updatedAt: isoDaysAgo(4),
    affectedPopulation: 3_200_000,
  },
  {
    id: "fac_009",
    title: "Thiruvananthapuram General Hospital",
    summary:
      "Well-equipped general facility but oncology services are saturated. Waitlist for chemotherapy cycles exceeds 4 weeks across southern Kerala.",
    category: "oncology",
    gapSeverity: "moderate",
    confidence: "govt-verified",
    source: "Kerala State Health Dept",
    country: "India",
    state: "Kerala",
    district: "Thiruvananthapuram",
    facilityType: "tertiary-hospital",
    beds: 1500,
    specialists: 22,
    lat: 8.5241,
    lon: 76.9366,
    occurredAt: isoDaysAgo(6),
    updatedAt: isoDaysAgo(2),
    affectedPopulation: 3_300_000,
  },
  {
    id: "fac_010",
    title: "Jamnagar PHC Cluster",
    summary:
      "Primary health centers in Jamnagar lack dialysis capability. CKD patients in Saurashtra region depend on private providers at 10x the cost.",
    category: "dialysis",
    gapSeverity: "severe",
    confidence: "estimated",
    source: "Gujarat Health Directorate",
    country: "India",
    state: "Gujarat",
    district: "Jamnagar",
    facilityType: "phc",
    beds: 30,
    specialists: 0,
    lat: 22.4707,
    lon: 70.0577,
    occurredAt: isoDaysAgo(12),
    updatedAt: isoDaysAgo(6),
    affectedPopulation: 2_100_000,
  },
  {
    id: "fac_011",
    title: "Nagpur Trauma Center",
    summary:
      "Dedicated emergency trauma center on NH44 corridor. Serves as referral point for Vidarbha region but faces critical blood bank shortages.",
    category: "emergency-trauma",
    gapSeverity: "moderate",
    confidence: "govt-verified",
    source: "MoHFW Infrastructure Report",
    country: "India",
    state: "Maharashtra",
    district: "Nagpur",
    facilityType: "specialty-center",
    beds: 250,
    specialists: 14,
    lat: 21.1458,
    lon: 79.0882,
    occurredAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(1),
    affectedPopulation: 4_600_000,
  },
  {
    id: "fac_012",
    title: "Tezpur CHC Maternity Unit",
    summary:
      "Community health center with a single maternity bed. Complicated deliveries require transfer across the Brahmaputra to Guwahati, adding 4-hour delay.",
    category: "maternity",
    gapSeverity: "critical",
    confidence: "survey-reported",
    source: "NFHS-5 survey data",
    country: "India",
    state: "Assam",
    district: "Sonitpur",
    facilityType: "chc",
    beds: 30,
    specialists: 1,
    lat: 26.6338,
    lon: 92.7837,
    occurredAt: isoDaysAgo(9),
    updatedAt: isoDaysAgo(4),
    affectedPopulation: 920_000,
  },
  {
    id: "fac_013",
    title: "Shimla IGMC Cardiology Wing",
    summary:
      "Only public cath lab in Himachal Pradesh. Mountain geography means cardiac emergencies in Kinnaur or Lahaul face 8+ hour road transfers.",
    category: "cardiology",
    gapSeverity: "critical",
    confidence: "govt-verified",
    source: "National Health Mission data",
    country: "India",
    state: "Himachal Pradesh",
    district: "Shimla",
    facilityType: "tertiary-hospital",
    beds: 900,
    specialists: 7,
    lat: 31.1048,
    lon: 77.1734,
    occurredAt: isoDaysAgo(4),
    updatedAt: isoDaysAgo(2),
    affectedPopulation: 6_800_000,
  },
  {
    id: "fac_014",
    title: "Koraput PHC Network",
    summary:
      "Primary health centers across southern Odisha lack pediatric specialists. Child malnutrition cases requiring clinical intervention face 250 km transfers.",
    category: "pediatrics",
    gapSeverity: "critical",
    confidence: "survey-reported",
    source: "NFHS-5 survey data",
    country: "India",
    state: "Odisha",
    district: "Koraput",
    facilityType: "phc",
    beds: 50,
    specialists: 0,
    lat: 18.8135,
    lon: 82.7104,
    occurredAt: isoDaysAgo(11),
    updatedAt: isoDaysAgo(5),
    affectedPopulation: 1_300_000,
  },
  {
    id: "fac_015",
    title: "AIIMS Bhopal General",
    summary:
      "AIIMS satellite campus with strong general coverage but growing gap in mental health beds. Serves as referral for 5 surrounding districts.",
    category: "mental-health",
    gapSeverity: "moderate",
    confidence: "govt-verified",
    source: "MoHFW Infrastructure Report",
    country: "India",
    state: "Madhya Pradesh",
    district: "Bhopal",
    facilityType: "tertiary-hospital",
    beds: 1000,
    specialists: 15,
    lat: 23.2599,
    lon: 77.4126,
    occurredAt: isoDaysAgo(6),
    updatedAt: isoDaysAgo(3),
    affectedPopulation: 2_300_000,
  },
  {
    id: "fac_016",
    title: "Dibrugarh General Hospital",
    summary:
      "District hospital in upper Assam with no orthopedic surgeon. Tea garden workers with fractures depend on private clinics or face 6-hour journey to Guwahati.",
    category: "orthopedics",
    gapSeverity: "critical",
    confidence: "crowd-sourced",
    source: "Community health worker reports",
    country: "India",
    state: "Assam",
    district: "Dibrugarh",
    facilityType: "district-hospital",
    beds: 200,
    specialists: 0,
    lat: 27.4728,
    lon: 94.912,
    occurredAt: isoDaysAgo(14),
    updatedAt: isoDaysAgo(7),
    affectedPopulation: 1_300_000,
  },
  {
    id: "fac_017",
    title: "Amritsar GMC Oncology",
    summary:
      "Government medical college with active radiotherapy unit. Serves as regional cancer hub but PET-CT capacity is insufficient for Punjab's caseload.",
    category: "oncology",
    gapSeverity: "moderate",
    confidence: "govt-verified",
    source: "Punjab Health Directorate",
    country: "India",
    state: "Punjab",
    district: "Amritsar",
    facilityType: "tertiary-hospital",
    beds: 1100,
    specialists: 11,
    lat: 31.634,
    lon: 74.8723,
    occurredAt: isoDaysAgo(5),
    updatedAt: isoDaysAgo(2),
    affectedPopulation: 2_400_000,
  },
  {
    id: "fac_018",
    title: "Muzaffarpur PHC Cluster",
    summary:
      "Primary centers in flood-prone north Bihar lack any emergency trauma capability. During monsoon, road access cuts off entirely for weeks.",
    category: "emergency-trauma",
    gapSeverity: "critical",
    confidence: "estimated",
    source: "Disaster management authority",
    country: "India",
    state: "Bihar",
    district: "Muzaffarpur",
    facilityType: "phc",
    beds: 40,
    specialists: 0,
    lat: 26.1209,
    lon: 85.3647,
    occurredAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(1),
    affectedPopulation: 4_800_000,
  },
  {
    id: "fac_019",
    title: "Hyderabad NIMS Dialysis Center",
    summary:
      "Large public dialysis center with 40 stations. Serves as model for Telangana but surrounding districts in Adilabad and Medak have zero public dialysis access.",
    category: "dialysis",
    gapSeverity: "moderate",
    confidence: "govt-verified",
    source: "Telangana Vaidya Vidhana Parishad",
    country: "India",
    state: "Telangana",
    district: "Hyderabad",
    facilityType: "specialty-center",
    beds: 300,
    specialists: 10,
    lat: 17.385,
    lon: 78.4867,
    occurredAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(1),
    affectedPopulation: 9_500_000,
  },
  {
    id: "fac_020",
    title: "Leh District Hospital",
    summary:
      "High-altitude district hospital with extremely limited specialist coverage. Any cardiology, oncology, or trauma case requires airlift or 2-day road transfer.",
    category: "general",
    gapSeverity: "critical",
    confidence: "govt-verified",
    source: "UT Ladakh Health Dept",
    country: "India",
    state: "Ladakh",
    district: "Leh",
    facilityType: "district-hospital",
    beds: 100,
    specialists: 3,
    lat: 34.1526,
    lon: 77.5771,
    occurredAt: isoDaysAgo(1),
    updatedAt: isoDaysAgo(0),
    affectedPopulation: 274_000,
  },
];
